const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let students=[], courses=[], enrollments=[], modalType="", editingId=null;

async function api(url,opts={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opts}); if(!r.ok){let e=await r.json().catch(()=>({detail:"Request failed"}));throw Error(e.detail||"Request failed")} return r.status===204?null:r.json()}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)}
function showPage(page){$$(".page").forEach(x=>x.classList.remove("active"));$("#"+page).classList.add("active");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("#pageTitle").textContent=page[0].toUpperCase()+page.slice(1); if(page==="students")loadStudents();if(page==="courses")loadCourses();if(page==="enrollments")loadEnrollments()}
$$(".nav").forEach(n=>n.onclick=()=>showPage(n.dataset.page));

async function loadDashboard(){const d=await api("/api/dashboard/stats");$("#stats").innerHTML=[["Students",d.students,"Active records"],["Courses",d.courses,"Available courses"],["Enrollments",d.enrollments,"Course registrations"],["Average CGPA",d.avg_cgpa,"Across all students"]].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join("");const max=Math.max(...d.departments.map(x=>x.count),1);$("#departments").innerHTML=d.departments.map(x=>`<div class="barrow"><div class="barrow-top"><b>${x.name}</b><span>${x.count}</span></div><div class="bar"><i style="width:${x.count/max*100}%"></i></div></div>`).join("");$("#recent").innerHTML=d.recent_students.map(s=>`<div class="mini"><div class="mini-avatar">${initials(s.name)}</div><div><b>${s.name}</b><small>${s.department} · Sem ${s.semester} · ${s.cgpa} CGPA</small></div></div>`).join("")}
function initials(n){return n.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}
async function loadStudents(){students=await api("/api/students?limit=500");renderStudents()}
function renderStudents(){const q=($("#studentSearch")?.value||"").toLowerCase();$("#studentsBody").innerHTML=students.filter(s=>(s.name+s.email+s.department).toLowerCase().includes(q)).map(s=>`<tr><td><b>${s.name}</b><small>${s.email}</small></td><td>${s.department}</td><td>Semester ${s.semester}</td><td><b>${s.cgpa}</b></td><td>${s.phone||"—"}</td><td><button class="action" onclick="editStudent(${s.id})">Edit</button> <button class="action danger" onclick="delStudent(${s.id})">Delete</button></td></tr>`).join("")}
function filterStudents(){renderStudents()}
async function loadCourses(){courses=await api("/api/courses");$("#coursesBody").innerHTML=courses.map(c=>`<tr><td><b>${c.code}</b></td><td>${c.name}</td><td>${c.credits}</td><td><button class="action" onclick="editCourse(${c.id})">Edit</button> <button class="action danger" onclick="delCourse(${c.id})">Delete</button></td></tr>`).join("")}
async function loadEnrollments(){[enrollments,students,courses]=await Promise.all([api("/api/enrollments"),api("/api/students?limit=500"),api("/api/courses")]);$("#enrollmentsBody").innerHTML=enrollments.map(e=>{let s=students.find(x=>x.id===e.student_id),c=courses.find(x=>x.id===e.course_id);return`<tr><td>#${e.id}</td><td>${s?.name||"Unknown"}</td><td>${c?.code||""} · ${c?.name||"Unknown"}</td><td>${e.grade||"—"}</td><td><button class="action danger" onclick="delEnrollment(${e.id})">Delete</button></td></tr>`}).join("")}

function openStudentModal(id=null){modalType="student";editingId=id;const s=id?students.find(x=>x.id===id):{};$("#modalTitle").textContent=id?"Edit student":"Add student";$("#modalForm").innerHTML=`<div class="form-grid">${field("name","Full name",s.name,true)}${field("email","Email",s.email,true)}${field("department","Department",s.department,true)}${field("semester","Semester",s.semester,true,"number")} ${field("cgpa","CGPA",s.cgpa,true,"number","0.01")} ${field("phone","Phone",s.phone||"")}<button class="primary form-submit field full">${id?"Save changes":"Create student"}</button></div>`;$("#modal").classList.add("show")}
function openCourseModal(id=null){modalType="course";editingId=id;const c=id?courses.find(x=>x.id===id):{};$("#modalTitle").textContent=id?"Edit course":"Add course";$("#modalForm").innerHTML=`<div class="form-grid">${field("code","Course code",c.code,true)}${field("name","Course name",c.name,true)}${field("credits","Credits",c.credits||3,true,"number")}<button class="primary form-submit field full">${id?"Save changes":"Create course"}</button></div>`;$("#modal").classList.add("show")}
function openEnrollmentModal(){modalType="enrollment";editingId=null;$("#modalTitle").textContent="Add enrollment";$("#modalForm").innerHTML=`<div class="form-grid"><div class="field full"><label>Student</label><select id="student_id" required>${students.map(s=>`<option value="${s.id}">${s.name} · ${s.department}</option>`).join("")}</select></div><div class="field full"><label>Course</label><select id="course_id" required>${courses.map(c=>`<option value="${c.id}">${c.code} · ${c.name}</option>`).join("")}</select></div>${field("grade","Grade","A")}</div><button class="primary form-submit">Create enrollment</button>`;$("#modal").classList.add("show")}
function field(id,label,value="",required=false,type="text",step=""){return`<div class="field"><label>${label}</label><input id="${id}" type="${type}" ${step?`step="${step}"`:""} value="${value??""}" ${required?"required":""}></div>`}
function closeModal(){$("#modal").classList.remove("show")}
async function submitModal(e){e.preventDefault();try{let body={};if(modalType==="student"){["name","email","department","semester","cgpa","phone"].forEach(k=>body[k]=$("#"+k).value);body.semester=+body.semester;body.cgpa=+body.cgpa;await api(editingId?`/api/students/${editingId}`:"/api/students",{method:editingId?"PUT":"POST",body:JSON.stringify(body)});toast(editingId?"Student updated":"Student created");loadStudents();loadDashboard()}else if(modalType==="course"){["code","name","credits"].forEach(k=>body[k]=$("#"+k).value);body.credits=+body.credits;await api(editingId?`/api/courses/${editingId}`:"/api/courses",{method:editingId?"PUT":"POST",body:JSON.stringify(body)});toast(editingId?"Course updated":"Course created");loadCourses();loadDashboard()}else{body={student_id:+$("#student_id").value,course_id:+$("#course_id").value,grade:$("#grade").value||null};await api("/api/enrollments",{method:"POST",body:JSON.stringify(body)});toast("Enrollment created");loadEnrollments();loadDashboard()}closeModal()}catch(e){toast(e.message)}}
function editStudent(id){openStudentModal(id)}function editCourse(id){openCourseModal(id)}
async function delStudent(id){if(!confirm("Delete this student?"))return;try{await api(`/api/students/${id}`,{method:"DELETE"});toast("Student deleted");loadStudents();loadDashboard()}catch(e){toast(e.message)}}
async function delCourse(id){if(!confirm("Delete this course?"))return;try{await api(`/api/courses/${id}`,{method:"DELETE"});toast("Course deleted");loadCourses();loadDashboard()}catch(e){toast(e.message)}}
async function delEnrollment(id){if(!confirm("Delete this enrollment?"))return;try{await api(`/api/enrollments/${id}`,{method:"DELETE"});toast("Enrollment deleted");loadEnrollments();loadDashboard()}catch(e){toast(e.message)}}
function ask(q){$("#chatInput").value=q;sendChat(new Event("submit"))}
async function sendChat(e){e.preventDefault();const input=$("#chatInput"),q=input.value.trim();if(!q)return;addBubble(q,"user");input.value="";addBubble("Thinking with database context…","ai","typing");try{const d=await api("/api/chat",{method:"POST",body:JSON.stringify({message:q})});$(".typing")?.remove();addBubble(d.answer,"ai")}catch(err){$(".typing")?.remove();addBubble("AI chat is unavailable. Check GEMINI_API_KEY in your .env file.","ai")}}
function addBubble(text,type,cls=""){const m=$("#messages"),b=document.createElement("div");b.className=`bubble ${type} ${cls}`;b.innerHTML=type==="user"?escapeHtml(text):`<b>CampusSphere AI</b><br>${escapeHtml(text).replace(/\n/g,"<br>")}`;m.appendChild(b);m.scrollTop=m.scrollHeight}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
loadDashboard();loadStudents();loadCourses();
